Repository God-saeng/Godsaeng-Backend, pull requests merged in 2023-01, with the labels that each got.

#8 Construct database
  .env.template
  .gitignore
  db/docker-compose.yml
  db/init.sql
Labels: size/S

#9 Add code to create user
  Cargo.toml
  src/main.rs
  src/services.rs
Labels: size/M

#22 Add GitHub Action configurations
  .github/settings/typos.toml
  .github/workflows/rust.yml
  .github/workflows/typos.yml
  src/main.rs
  src/services.rs
Labels: size/L
