Repository God-saeng/Godsaeng-Backend, pull requests merged in 2023-02, with the labels that each got.

#10 Add code to patch user
  src/main.rs
  src/services.rs
Labels: size/M

#11 Add code to delete user
  src/main.rs
  src/services.rs
Labels: size/S

#13 Add code to create event
  Cargo.toml
  db/init.sql
  src/events.rs
  src/main.rs
Labels: size/M

#14 Add code to patch event
  src/events.rs
  src/main.rs
Labels: size/S

#15 Add code to delete event
  src/events.rs
  src/main.rs
Labels: size/S

#16 Fix simple bugs
  src/main.rs
  src/users.rs
Labels: size/XS

#23 Add DB scripts
  .env.template
  db/docker-compose.yml
  migrations/20230204082932_create_userInfo_table.sql
  migrations/20230204083035_insert_admin_to_userInfo.sql
  migrations/20230204083105_create_event_table.sql
  scripts/init_db.sh
Labels: size/L

#24 Refactor code structure
  Cargo.toml
  src/lib.rs
  src/main.rs
  src/routes/events.rs
  src/routes/mod.rs
  src/routes/users.rs
  src/runner.rs
Labels: size/M

#28 Change policy to allow any branches run CIs on pull request
  .github/workflows/rust.yml
Labels: size/XS

#25 Fix few mistakes
  scripts/init_db.sh
  src/routes/events.rs
  src/routes/users.rs
Labels: size/M
